# Generated by Django 5.0.6 on 2024-07-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='attachment',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
