# Generated by Django 5.0.6 on 2024-07-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='delivery_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.personaddress'),
        ),
    ]
