# Generated by Django 5.0.6 on 2024-07-21 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_person_attachment_personaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='delivery_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.personaddress'),
        ),
    ]
