# Generated by Django 5.1.3 on 2025-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_group_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='attachment',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
